version: '3.8'
services:
  firefox:
    image: 'jlesage/firefox'
    container_name: firefox
    ports:
      - '5800:5800'
    volumes:
      - '/home/username/docker/firefox/config:/config:rw'
    restart: unless-stopped